### ISSUE TITLE
bwr's not loading

### ISSUE THREAD

**Issue by mario999-stack** [Seamusmario/BonziWORLD-Revived#5]
this issue: critical is the severe issue. pls fix this asap
3 low, 3 moderate, 5 high, 1 critical

**Comment by Seamusmario** [comment]
npm audit

**Comment by mario999-stack** [comment]
beta design:
unworking
classic design:
unworking

**Comment by Seamusmario** [comment]
i wonder if you even know how to play this

**Comment by mario999-stack** [comment]
when ur css was wip i checked it out and a lot of assets were unloaded
