### ISSUE TITLE
beta style is broken and unsupported

### ISSUE THREAD

**Issue by mario999-stack** [Seamusmario/BonziWORLD-Revived#6]
if u dont mind would u delete it

**Comment by Seamusmario** [comment]
what do you mean? be more specific

**Comment by mario999-stack** [comment]
As I said,
The beta CSS design is actually going to be a hard one, you cant really make it if your going to add the CSS. It will take up to some months or years.

**Comment by Seamusmario** [comment]
I have updated this not long ago.

**Comment by mario999-stack** [comment]
The CSS is a _broken productive_, I would not recommend this Beta CSS.

**Comment by Seamusmario** [comment]
It should look like this.
![chrome_IholaIMfhD](https://user-images.githubusercontent.com/33694155/122293468-07d1c800-cec5-11eb-9f22-5c304eb598ea.png)

**Comment by mario999-stack** [comment]
Interesting.

**Comment by mario999-stack** [comment]
However, the site link maybe is ngrok

**Comment by mario999-stack** [comment]
Also, its medikk.

**Comment by Seamusmario** [comment]
Yes, the site is running in ngrok, due to my safety concerns. http://d27414a54924.ngrok.io

**Comment by Seamusmario** [comment]
What is the current status on this bug?
